Programació per a la ciència de dades - PAC1
============================

En aquest Notebook trobareu un conjunt d'exercicis que conformen la primera activitat d'avaluació contínua (PAC) de l'assignatura.

Per a cada exercici, tingueu en compte que:

* **És necessari incloure comentaris** del vostre codi, que expliquin com heu implementat la solució del problema plantejat.
* **És imprescindible** citar les referències consultades per realitzar l'activitat. Es valorarà que el codi proporcionat solucioni el problema proposat i també la qualitat del codi (comentaris, llegibilitat, claredat, ús de les estructures de dades adequades, bona nomenclatura de les variables i funcions, seguiment del PEP8, etc.).

Veureu que cadascuna de les activitats té associada una puntuació, que indica el pes que té l'activitat sobre la nota de la PAC.

A més, totes les activitats tenen una etiqueta, que indica els recursos necessaris per dur-la a terme. Hi ha tres possibles etiquetes:

* <span style="font-family: Courier New; background-color: #82b74b; color: #000000; padding: 3px;">SM</span> **Només materials**: les eines necessàries per realitzar l'activitat es poden trobar en els materials de l'assignatura (considerarem també els materials de l'assignatura Fonaments de Programació, així com les lectures obligatòries de material extern que s'indiquen en els notebooks).
* <span style="font-family: Courier New; background-color: #ffcc5c; color: #000000; padding: 3px;">EG</span> **Consulta externa guiada**: l'activitat pot requerir fer ús d'eines que no es troben en els materials de l'assignatura, però l'enunciat conté indicacions d'on o com trobar la informació addicional necessària per resoldre l'activitat.
* <span style="font-family: Courier New; background-color: #f2ae72; color: #000000; padding: 3px;">EI</span> **Consulta externa independent**: l'activitat pot requerir fer ús d'eines que no es troben en els materials de l'assignatura, i l'enunciat pot no incloure la descripció d'on o com trobar aquesta informació addicional. Serà necessari que l'estudiant busqui aquesta informació utilitzant els recursos que s'han explicat en l'assignatura.

És important notar que aquestes etiquetes no indiquen el nivell de dificultat de l'exercici, sinó únicament la necessitat de consulta de documentació externa per a la seva resolució. A més, recordeu que les **etiquetes són informatives**, però podeu consultar referències externes sempre que ho desitgeu (encara que no s'indiqui explícitament) o potser podreu realitzar una activitat sense consultar cap tipus de documentació. Per exemple, per resoldre una activitat que només requereixi els materials de l'assignatura, podeu consultar referències externes si ho desitgeu, ja sigui tant per ajudar en la resolució com per ampliar coneixements.



---

## Abans de començar

Llegiu atentament els paràgrafs que segueixen, relacionats amb l'originalitat en les activitats, abans de començar a treballar en la PEC. Si us sorgeix qualsevol dubte dirigiu-vos al professor col·laborador de l'assignatura abans de continuar amb l'activitat.

<div class="alert alert-block alert-success"> La manca d'originalitat es produeix quan en una activitat apareix contingut que no ha estat elaborat de forma individual per l'estudiant i no es referencia adequadament el seu origen. O bé quan, encara que el contingut extern estigui referenciat, aquest és tan extens que no és possible considerar l'estudiant l'autor o autora de l'activitat. <br /><br /> Així, alguns exemples de comportaments inadequats degut a manca d'originalitat són: <ol> <li>Crear la solució d'un exercici de la PEC en col·laboració entre diversos estudiants.</li> <li>Incloure un exercici de la PEC que utilitza codi trobat a internet sense citar la font.</li> <li>Compartir la vostra solució de la PEC amb altres estudiants de l'assignatura.</li> </ol> </div>

## Instruccions de lliurament

Per procedir a l'entrega de l'activitat és necessari realitzar els següents passos:

1. Comproveu que el notebook s'executa correctament en Google Colaboratory. És important que abans d'entregar la vostra PEC us assegureu que la versió final del codi s'executa correctament en la seva totalitat. Per a això, es recomana fer una execució completa des de zero del notebook fent clic a <i>"Entorn d'execució i executar totes"</i>, i comprovant que totes les cel·les del notebook s'executen correctament.

2. Confirmeu que sou els autors únics de la PEC i que aquesta inclou totes les cites a recursos externs que s'hagin utilitzat per elaborar-la. Amb la finalitat de confirmar que sou els autors únics de l'activitat, afegiu el vostre nom complet a la cel·la següent.

3. Entregueu el notebook corresponent a la resolució de la PEC a través del Registre d'Avaluació Contínua de l'aula. Podeu descarregar el notebook mitjançant <i>"Arxiu, descarregar i descarregar .ipynb"</i>

<div class="alert alert-block alert-warning">Jo, Albert Lozano Valverde, confirmo que he elaborat de forma individual totes les activitats resoltes en aquesta PEC i que he inclòs les cites a totes les fonts externes que he utilitzat per resoldre les activitats. </div>


## Type hints

Us recomanem resoldre aquesta PEC utilitzant type hints. Podem entendre els type hints de Python com una solució formal per indicar estèticament el tipus de valor dins del codi Python. Us recomanem la visualització del següent [vídeo](https://www.youtube.com/watch?v=j0dy8Q9VIPk) per a una introducció als type hints en Python, i per entendre per què són interessants.

##  Enunciat

Els següents exercicis es realitzaran utilitzant el dataset denuncies_sancions.csv proporcionat juntament amb la PEC, i que conté informació sobre diferents sancions de trànsit a la ciutat de Barcelona, obtinguda de la web d'Open Data de l'Ajuntament de Barcelona. Cada fila representa una sanció.

Els camps del dataset són els següents:

Infraccio_codi: Codi intern de la infracció.

*   Infraccio_Desc_Curta_CA: Descripció curta de la infracció en català.
*   Infraccio_Desc_Curta_ES: Descripció curta de la infracció en espanyol.
*   Infraccio_Desc_Llarga_ES: Descripció detallada de la infracció en espanyol.
*   Data_Inici_Vigencia: Data aplicació de la sanció.
*   Data_Fi_Vigencia: Data fi de la vigència de la sanció (per defecte, sempre 31/12/9999)
*   Article: Codi de l'article legal pel qual s'aplica la sanció.
*   Normativa: Procedència de la normativa del qual procedeix l'article.
*   Import_Nominal_?: Import de la sanció.
*   Tipus_Infraccio: Codi del tipus d'infracció.
*   Punts_A_Retirar: Punts a retirar al conductor.
*   Autoritat: Autoritat que signa la sanció.

**IMPORTANT**: La càrrega del dataset s'ha de fer utilitzant **rutes relatives**, heu de carregar el fitxer tenint en compte que treballeu (el vostre notebook es troba) en una carpeta que conté la carpeta data i l'arxiu de dades corresponent.

Només heu de carregar el fitxer una sola vegada en el primer exercici.

## Exercici 1

Carregueu el dataset de manera que obtingueu un objecte de tipus dataframe.

Un cop carregat el dataset, resolgueu les següents qüestions:

1. Visualitzeu els primers 90 registres.
2. Retorneu el nombre de diferents descripcions de sancions en català.
3. Converteix la columna de data d'inici de la sanció al format Dia/Mes/Any (dd/mm/aaaa).
4. Comproveu que tots els valors de fi de vigència són iguals. En cas afirmatiu, elimineu la columna.
5. Visualitzeu la sanció amb l'import més elevat.
6. Modifiqueu el títol de la columna "Infraccio_Codi" per "Codi".

Pista 1: Recordeu que podeu utilitzar biblioteques com pandas per carregar el conjunt de dades de manera senzilla i obtenir un dataframe.

Pista 2: El type hint d'un dataframe és pd.DataFrame.

**Tots els exercicis s'han de resoldre a partir del dataframe obtingut al finalitzar aquest exercici i no carregar-lo cada vegada que s'hagi d'utilitzar.**

<span style="font-family: Courier New; background-color: #82b74b; color: #000000; padding: 3px;">SM</span> (**2 punts**)

<div style="background-color: #fcf2f2; border-color: #dfb5b4; border-left: 5px solid #dfb5b4; padding: 0.5em;">
<strong>Solució</strong>
</div>

In [1]:
import pandas as pd
df=pd.read_csv('data/denuncies_sancions.csv',sep=";",encoding="ANSI") #he utilitzat el encoding ansi perque tenia problemes amb el caracter "ç"
df.head(90)

,Infraccio_Codi,Infraccio_Desc_Curta_CA,Infraccio_Desc_Curta_ES,Infraccio_Desc_Llarga_CA,Infraccio_Desc_Llarga_ES,Data_Inici_Vigencia,Data_Fi_Vigencia,Article,Normativa,Import_Nominal_?,Tipus_Infraccio,Punts_A_Retirar,Autoritat
0,910,NO IDENTIFIC CONDUCT RESPONS INFRACCIO,NO IDENTIFIC CONDUCT RESPONS INFRACCION,NaN,-,2005-03-16,9999-12-31,77. J,LSV,301,E,0,Il.lm./a Sr./a Regidor/a del Districte
1,912,NO IDENTIFICAR EL CONDUCTOR RESPONSABLE DE LA ...,NO IDENTIFICAR AL CONDUCTOR RESPONSABLE DE LA ...,NaN,-,1900-01-03,9999-12-31,77. J,LSV,301,E,0,Il.lm./a Sr./a Regidor/a del Districte
2,913,NO IDENTIFICAR EL CONDUCTOR RESPONSABLE DE LA ...,NO IDENTIFICAR AL CONDUCTOR RESPONSABLE DE LA ...,NaN,-,1900-01-03,9999-12-31,77. J,LSV,1000,E,0,Il.lm./a Sr./a Regidor/a del Districte
3,1001,INSTAL SENYAL V PUB SENSE PERMIS O CAUSA,INSTAL SENAL V PUBL SIN PERMISO O CAUSA,Instal.lar senyalitzacio en una via publica se...,-,2003-05-21,9999-12-31,73.C A,OCVV,90,E,0,Il.lm./a Sr./a Regidor/a del Districte
4,1002,COL.LOC SOBRE SENYAL/COSTAT OBJ PUBLICIT,COLOCAR SOBRE SENAL/LADO OBJETO PUBLICIT,Col.locar publicitat a sobre o al costat dels ...,-,2003-05-21,9999-12-31,73.B A,OCVV,90,E,0,Il.lm./a Sr./a Regidor/a del Districte
...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,1095,EFECT CAR/DES SENSE FER-HO COSTAT VORERA,EFECT CAR/DES SIN HACERLO AL LADO ACERA,Carregar o descarregar sense fer-ho pel costat...,-,2002-01-01,9999-12-31,73.1 A,OCVV,60,E,0,Il.lm./a Sr./a Regidor/a del Districte
86,1096,EFECT CAR/DES DESTORB CIRCULAC VIAN/VEH,EFECT CAR/DES ENTORPEC CIRCULAC PEAT/VEH,Carregar o descarregar dificultant la circulac...,-,2002-01-01,9999-12-31,73.1 A,OCVV,60,E,0,Il.lm./a Sr./a Regidor/a del Districte
87,1097,EFECT CAR/DES SENSE UTILIT MITJ ADEQUATS,EFECT CAR/DES SIN UTILIZ MEDIOS ADECUAD,Carregar i descarregar sense utilitzar els mit...,-,2002-01-01,9999-12-31,73.1 A,OCVV,60,E,0,Il.lm./a Sr./a Regidor/a del Districte
88,1098,COL.LOCAR CONTENIDOR PERJUDICANT TRANSIT,COLOCAR CONTENEDOR PERJUDICANDO TRAFICO,Contenidor col.locat a la via publica fora de ...,-,2003-05-21,9999-12-31,73.1 A,OCVV,90,E,0,Il.lm./a Sr./a Regidor/a del Districte
89,1099,SENYALITZ RESERVA ESTAC SENSE LLICENCIA,SENALIZAR RESERVA ESTAC SIN LICENCIA,Senyalitzar una reserva d'estacionament o d'es...,-,2002-01-01,9999-12-31,73.1 A,OCVV,150,M,0,Il.lm./a Sr./a Regidor/a del Districte

In [2]:
a=df["Infraccio_Desc_Curta_CA"].nunique()#nunique es una funcio de df que et dona el numero de valors unics que hi ha en un df
print("Descripcions curtes tennim :"+str(a))
a=df["Infraccio_Desc_Llarga_CA"].nunique()
print("\n Descripcions llargques tennim :"+str(a))

Descripcions curtes tennim :588

 Descripcions llargques tennim :590

In [3]:
import datetime #he importat datetime una llibreria pensada per canviar el format de les dades, he mostrat les tres primeres perque es vegui que ho fa bé
df["Data_Inici_Vigencia"]=df["Data_Inici_Vigencia"].apply(lambda x: datetime.datetime.strptime(x, '%Y-%m-%d').strftime('%d/%m/%y'))
df.head(3)

,Infraccio_Codi,Infraccio_Desc_Curta_CA,Infraccio_Desc_Curta_ES,Infraccio_Desc_Llarga_CA,Infraccio_Desc_Llarga_ES,Data_Inici_Vigencia,Data_Fi_Vigencia,Article,Normativa,Import_Nominal_?,Tipus_Infraccio,Punts_A_Retirar,Autoritat
0,910,NO IDENTIFIC CONDUCT RESPONS INFRACCIO,NO IDENTIFIC CONDUCT RESPONS INFRACCION,NaN,-,16/03/05,9999-12-31,77. J,LSV,301,E,0,Il.lm./a Sr./a Regidor/a del Districte
1,912,NO IDENTIFICAR EL CONDUCTOR RESPONSABLE DE LA ...,NO IDENTIFICAR AL CONDUCTOR RESPONSABLE DE LA ...,NaN,-,03/01/00,9999-12-31,77. J,LSV,301,E,0,Il.lm./a Sr./a Regidor/a del Districte
2,913,NO IDENTIFICAR EL CONDUCTOR RESPONSABLE DE LA ...,NO IDENTIFICAR AL CONDUCTOR RESPONSABLE DE LA ...,NaN,-,03/01/00,9999-12-31,77. J,LSV,1000,E,0,Il.lm./a Sr./a Regidor/a del Districte

In [4]:
if df["Data_Fi_Vigencia"].nunique()==1: #mirem si nomes hi ha un unic valor en cas que si eliminem la columna
    df.drop("Data_Fi_Vigencia", axis=1, inplace=True)

In [5]:
df.head(3)

,Infraccio_Codi,Infraccio_Desc_Curta_CA,Infraccio_Desc_Curta_ES,Infraccio_Desc_Llarga_CA,Infraccio_Desc_Llarga_ES,Data_Inici_Vigencia,Article,Normativa,Import_Nominal_?,Tipus_Infraccio,Punts_A_Retirar,Autoritat
0,910,NO IDENTIFIC CONDUCT RESPONS INFRACCIO,NO IDENTIFIC CONDUCT RESPONS INFRACCION,NaN,-,16/03/05,77. J,LSV,301,E,0,Il.lm./a Sr./a Regidor/a del Districte
1,912,NO IDENTIFICAR EL CONDUCTOR RESPONSABLE DE LA ...,NO IDENTIFICAR AL CONDUCTOR RESPONSABLE DE LA ...,NaN,-,03/01/00,77. J,LSV,301,E,0,Il.lm./a Sr./a Regidor/a del Districte
2,913,NO IDENTIFICAR EL CONDUCTOR RESPONSABLE DE LA ...,NO IDENTIFICAR AL CONDUCTOR RESPONSABLE DE LA ...,NaN,-,03/01/00,77. J,LSV,1000,E,0,Il.lm./a Sr./a Regidor/a del Districte

In [6]:
float(df["Import_Nominal_?"].max()) #utilitzem max per obtienir el maxim

6000.0

In [7]:
df=df.rename(columns={"Infraccio_Codi": "Codi"})#utilitzem rename per canviar de nom

## Exercici 2

2.1 Creeu un diccionari utilitzant Dictionary Comprehensions tal que cada relació clau-valor sigui cadascuna de les descripcions curtes i el valor el nombre de registres en què apareix aquesta descripció curta:

*   Les claus corresponguin a les descripcions curtes en espanyol de la sanció (**Infraccio_Desc_Curta_ES**).
*   Els seus valors corresponguin al nombre de registres de cada descripció curta.

2.2 Mostreu les 15 primeres entrades del diccionari (clau i valor) un cop l'hem ordenat segons el nom de registres que contenen cada número (de més a menys).

<span style="font-family: Courier New; background-color: #82b74b; color: #000000; padding: 3px; ">SM</span> **(1 punt)**

<div style="background-color: #fcf2f2; border-color: #dfb5b4; border-left: 5px solid #dfb5b4; padding: 0.5em;">
<strong>Solució</strong>
</div>

In [8]:
dict_complet=df['Infraccio_Desc_Curta_ES'].value_counts().to_dict()#value_counts ens dona una serie on el index es el valor de la serie anterior i el valor es el numero de vegades que esta,
                                                                   #to_dict ho transforma a dict

In [9]:
df['Infraccio_Desc_Curta_ES'].value_counts()[0:15].to_dict() #faig el mateix amb els 15 primers

{'SUPERAR LIMITE VELOCIDAD VEHIC ESPECIAL': 6,
 'EXCESO VELOCIDAD POR SENAL/CONDUCT/VEHIC': 5,
 'SUPERAR LIMITE VELOCIDAD SENAL ESPECIFIC': 3,
 'SUPERAR LIMITE VELOCIDAD NORMA GENERAL': 2,
 'CIRCUL VEH NO AUTORIZ POR CARRIL RESERV': 2,
 'CONDUCIR MODO MANIFIESTAMENTE TEMERARIO': 2,
 'NO OBEDECE LUZ ROJA SEMAFORO CON PELIGRO': 2,
 'NO IDENTIFICAR AL CONDUCTOR RESPONSABLE DE LA INFRACCION': 2,
 'EXCESO VELOCIDAD POR RAZON DE VIA': 2,
 'CIRCULAR INCUMPLIENDO CONDIC.DE AUTORIZACION ADM.QUE HABILIT': 1,
 'BICICLETA HACIENDO CAMBIO SENTIDO DE LA MARCHA CON PELIGRO': 1,
 'CONDUCIR BICI/VMP/CICLO MANERA MANIFIESTAMENTE TEMERARIA': 1,
 'INVADIR BICICLETA SENTIDO CONTRARIO CIRCULACION CON PELIGRO': 1,
 'CIRCULAR BICICLETA EN ENCUENTRO VIAS EN SENTIDO CONTRARIO': 1,
 'CIRCULAR BICICLETA SENTIDO CONTRARIO EN VIA VARIAS CALZADAS': 1}

## Exercici 3

Utilitzant el *dataframe* obtingut en l'Exercici 1

creeu una funció tal que tingui com a paràmetres d'entrada:
* L'estructura de dades (dataframe obtingut en l'Exercici 1)
* Codi d'infracció
* Normativa

La funció ens retornarà un **boolean** que indiqui si la infracció que correspon al codi compleix amb la Normativa (legislació) de la columna "Normativa" (LSV o OCVV o RGC).

Si no s'introdueix cap valor en el paràmetre de normativa, que per defecte assigni el valor 'LSV'.

Per mostrar el resultat, retorna un text complet com aquest: "Per a la infracció amb codi 'codi_infraccio' amb data de vigència 'Data_inici_vigencia' compleix la normativa 'paràmetre de la normativa/no compleix la normativa". L'última part del text dependrà de si compleix o no la normativa que s'ha passat com a paràmetre.

<span style="font-family: Courier New; background-color: #82b74b; color: #000000; padding: 3px; ">SM</span> **(1 punt)**

<div style="background-color: #fcf2f2; border-color: #dfb5b4; border-left: 5px solid #dfb5b4; padding: 0.5em;">
<strong>Solució</strong>
</div>

In [10]:

def valorador(df,cd,nor="LSV"): #posem "LSV" com a default de normativa
    try:
        filtrat=df[df["Codi"]==cd] 
        var=filtrat["Normativa"].iloc[0]==nor#Busquem el codi al df i ens quedem amb la columna normativa i  el primer valor que hauria de ser el unic, y comparem si es igual a la normativa donada
    except: 
        print("El codi "+ str(cd) + " no existeix" )# en cas que el codi no exiteixi t¡fem aixo
        return
    data=df[df["Codi"]==cd]["Data_Inici_Vigencia"].iloc[0]# extreimem la data d'inici de vigencia fen el mateix que abans
    if(var): #comprobem si complim la normativa per canviar el print final
        text="compleix la normativa"
    else:
        text="no compleix la normativa"
    print("Per a la infracció amb codi "+str(cd) + " amb data de vigència " +data+ " "+ text)

In [11]:
valorador(df,1,"OCVV")
valorador(df,912,"OCVV")
valorador(df,912)

El codi 1 no existeix
Per a la infracció amb codi 912 amb data de vigència 03/01/00 no compleix la normativa
Per a la infracció amb codi 912 amb data de vigència 03/01/00 compleix la normativa

## Exercici 4

Utilitzant el *dataframe* obtingut en l'Exercici 1

3.1 Creeu una funció tal que tingui com a paràmetres d'entrada:
* tipus_d'infracció
* punts_a_retirar

La funció retornarà totes les infraccions que compleixin que la columna "Tipus_Infraccio" sigui igual al paràmetre "tipus_d'infracció" i que el paràmetre "punts_a_retirar" superi el valor de la columna "Punts_A_Retirar".

Imprimiu el resultat amb el format: "L'infracció amb codi {Infraccio_Codi} ha retirat al conductor {Punts_A_Retirar} per {Infraccio_Desc_Llarga_CA}".

Realitzeu la prova per al tipus d'infracció M i més de 3 punts.


<span style="font-family: Courier New; background-color: #82b74b; color: #000000; padding: 3px; ">SM</span> **(1.5 punts)**

<div style="background-color: #fcf2f2; border-color: #dfb5b4; border-left: 5px solid #dfb5b4; padding: 0.5em;">
<strong>Solució</strong>
</div>

In [12]:
def infraccions(tp,pnt):
    temp=df[(df["Tipus_Infraccio"]==tp) & (df["Punts_A_Retirar"]>pnt)] #filtrem per les dos condicions donades
    for index, row in temp.iterrows(): #iterem i fem els prints corresponents
        print("L'infracció amb codi "+str(row["Codi"])+" ha retirat al conductor "+str(row["Punts_A_Retirar"])+" per "+str(row["Infraccio_Desc_Llarga_CA"]))

In [13]:
infraccions("M",3)

L'infracció amb codi 1216 ha retirat al conductor 4 per Circular amb exces de velocitat per raons de via.
L'infracció amb codi 1217 ha retirat al conductor 4 per Circular amb exces de velocitat per raons de senyal, conductor o vehicle.
L'infracció amb codi 1218 ha retirat al conductor 4 per Circular amb exces de velocitat per raons de senyal, conductor o vehicle (mes de 3.500 kg o mes de 9 passatgers).
L'infracció amb codi 1219 ha retirat al conductor 6 per Circular amb exces de velocitat per raons de via.
L'infracció amb codi 1220 ha retirat al conductor 6 per Circular amb exces de velocitat per raons de senyal, conductor o vehicle.
L'infracció amb codi 1221 ha retirat al conductor 6 per Circular amb exces de velocitat per raons de senyal, conductor o vehicle (mes de 3.500 kg o mes de 9 passatgers).
L'infracció amb codi 1222 ha retirat al conductor 6 per Circular amb exces de velocitat per raons de via.
L'infracció amb codi 1223 ha retirat al conductor 6 per Circular amb exces de velocitat per raons de senyal, conductor o vehicle.
L'infracció amb codi 1224 ha retirat al conductor 6 per Circular amb exces de velocitat per raons de senyal, conductor o vehicle (mes de 3.500 kg o mes de 9 passatgers).
L'infracció amb codi 1230 ha retirat al conductor 4 per Circular amb exces de velocitat per raons de via (mes de 3.500 kg o mes de 9 passatgers).
L'infracció amb codi 1231 ha retirat al conductor 6 per Circular amb exces de velocitat per raons de via (mes de 3.500 kg o mes de 9 passatgers).
L'infracció amb codi 1232 ha retirat al conductor 6 per Circular amb exces de velocitat per raons de via (mes de 3.500 kg o mes de 9 passatgers).
L'infracció amb codi 1304 ha retirat al conductor 6 per Conduir un vehicle de dues rodes de manera manifestament temeraria.
L'infracció amb codi 1305 ha retirat al conductor 6 per Conduir un vehicle de manera manifestament temeraria.
L'infracció amb codi 1306 ha retirat al conductor 6 per Llencar a la via publica o als seus voltants un objecte que pugui ocasionar un incendi o un accident de circulacio.
L'infracció amb codi 1327 ha retirat al conductor 4 per Circular amb un menor d'edat d'alcada igual o inferior a 135 centimetres amb un sistema de retencio infantil homologat a l'efecte en el seient davanter del vehicle en suposits no autoritzats
L'infracció amb codi 1337 ha retirat al conductor 4 per Circular amb un menor edat  alcada igual o inferior a 135 centimetres sense utilitzar, o no fer-ho de forma adequada, un sistema de retencio infantil homologat a efecte
L'infracció amb codi 1340 ha retirat al conductor 6 per Envair el sentit contrari de la circulacio amb perill.
L'infracció amb codi 1366 ha retirat al conductor 6 per Entaular competencia de velocitat entre vehicles a la via publica o zona d'us public.
L'infracció amb codi 1386 ha retirat al conductor 4 per Avancar en revolts, canvis de rasant i en llocs de visibilitat reduida.
L'infracció amb codi 1395 ha retirat al conductor 6 per Excedir en mes d'un 50% els temps de conduccio establerts en la legislacio sobre transports terrestres.
L'infracció amb codi 1396 ha retirat al conductor 6 per Minorar en mes d'un 50% els periodes de descans establerts en la legislacio sobre transports terrestres.
L'infracció amb codi 1401 ha retirat al conductor 4 per Circular sense utilitzar, degudament cordats, el conductor el cinturo de seguretat.
L'infracció amb codi 1402 ha retirat al conductor 4 per No utilitzar el conductor casc de proteccio circulant en ciclomotor.
L'infracció amb codi 1403 ha retirat al conductor 4 per No utilitzar el conductor casc de proteccio circulant en motocicleta.
L'infracció amb codi 1408 ha retirat al conductor 4 per No utilitzar el conductor casc de proteccio circulant en vehicles de tres rodes o quadricicles, o vehicles especials tipus quad.
L'infracció amb codi 1444 ha retirat al conductor 6 per Conduir vehicles  que portin  instal.lats inhibidors de radar o cinemometres  o altres mecanismes per interferir en correcte  funcionament sistemes  vigilancia de transit
L'infracció amb codi 1446 ha retirat al conductor 4 per No utilitzar el conductor del vehicle que n'ha sortit i ocupa la calcada o el voral de la via, una armilla reflectora de visibilitat alta
L'infracció amb codi 1474 ha retirat al conductor 6 per Circular per una placa / glorieta / trobada de vies, en sentit contrari de l'estipulat.
L'infracció amb codi 1485 ha retirat al conductor 6 per Circular en sentit contrari de l'estipulat en una via dividida en mes d'una calcada.
L'infracció amb codi 1486 ha retirat al conductor 4 per Circular darrere d'un altre vehicle sense mantenir la distancia que li permeti aturar-se, sense col.lisionar, en cas de frenada brusca del que el precedeix
L'infracció amb codi 1503 ha retirat al conductor 4 per Desobeir els SENYALS i/o les ORDRES D'UN AGENT que regula la circulacio AMB PERILL.
L'infracció amb codi 1504 ha retirat al conductor 4 per No obeir el conductor d'un ciclomotor o motocicleta el LLUM VERMELL d'un semafor AMB PERILL.
L'infracció amb codi 1505 ha retirat al conductor 4 per No obeir el conductor d'un vehicle el LLUM VERMELL d'un semafor AMB PERILL.
L'infracció amb codi 1506 ha retirat al conductor 4 per No cedir el pas en interseccio regulada amb senyal de CEDIU EL PAS O STOP obligant a la resta de conductor a fer maniobres brusques AMB RISC DE COL.LISIO.
L'infracció amb codi 1549 ha retirat al conductor 4 per No utilitzar el conductor casc de proteccio homologat i certificat.
L'infracció amb codi 1550 ha retirat al conductor 4 per No utilitzar el conductor adequadament el casc de proteccio (especifiqueu-ne l'us inadequat).
L'infracció amb codi 1576 ha retirat al conductor 4 per Avancar un vehicle a bicicleta o ciclomotor posant en perill o entorpint a ciclistes que circulen en sentit contrari, inclos arcen
L'infracció amb codi 1583 ha retirat al conductor 4 per No respectar la prioritat de pas dels ciclistes amb perill.
L'infracció amb codi 1584 ha retirat al conductor 4 per Retrocedir en una via on no estigui autoritzat amb perill.
L'infracció amb codi 1686 ha retirat al conductor 6 per Avancar un vehicle a bicicleta o ciclomotor sense deixar una amplada de seguretat d'almenys 1,5 metres
L'infracció amb codi 1687 ha retirat al conductor 6 per Conduir un vehicle subjectant amb la ma dispositius de telefonia mobil
L'infracció amb codi 3281 ha retirat al conductor 4 per Conduir un vehicle. Taxa alcohol en aire expirat superior a 0,15 mg/l, conductor professional, servei public, mercaderies perilloses, transports especials, novells...
L'infracció amb codi 3282 ha retirat al conductor 4 per Conductor reincident. Conduir un vehicle. Taxa d'alcohol en aire expirat superior a 0,15 mg/l, conductor professional, servei public, mercaderies perilloses, transports especials, novells
L'infracció amb codi 3284 ha retirat al conductor 4 per Conduir un vehicle. Taxa d'alcohol en aire expirat superior a 0,25 mg/l
L'infracció amb codi 3285 ha retirat al conductor 4 per Conductor reincident. Conduir un vehicle. Taxa d'alcohol en aire expirat superior a 0,25 mg/l
L'infracció amb codi 3287 ha retirat al conductor 6 per Conduir un vehicle. Taxa d'alcohol en aire expirat superior a 0,30 mg/l, conductor professional, servei public, mercaderies perilloses, transports especials, novells...
L'infracció amb codi 3288 ha retirat al conductor 6 per Conductor reincident. Conduir un vehicle. Taxa d'alcohol en aire expirat superior a 0,30 mg/l, conductor professional, servei public, mercaderies perilloses, transports especials, novells
L'infracció amb codi 3290 ha retirat al conductor 6 per Conduir un vehicle. Taxa d'alcohol en aire expirat superior a 0,50 mg/l
L'infracció amb codi 3291 ha retirat al conductor 6 per Conductor reincident. Conduir un vehicle. Taxa d'alcohol en aire expirat superior a 0,50 mg/l
L'infracció amb codi 3293 ha retirat al conductor 6 per No sotmetre's a les proves de deteccio alcoholica, el conductor d'un vehicle
L'infracció amb codi 3296 ha retirat al conductor 6 per Conduir un vehicle amb presencia de drogues a l'organisme
L'infracció amb codi 3299 ha retirat al conductor 6 per No sotmetre's, el conductor un vehicle  a les proves per a la deteccio de drogues a organisme

## Exercici 5

Us demanem el següent:

5.1 Obteniu la infracció amb l'import nominal (*Import_Nominal*) més alt.  
5.2 Implementar una funció que rebi com a paràmetre d'entrada una paraula i que comprovi si la paraula apareix a la columna "Infraccio_Desc_curta_ES". Que mostri totes les infraccions amb la coincidència.  
5.3 Utilitzant una *dict comprehension* creeu un diccionari on les claus siguin els codis d'infracció (*Infraccio_Codi*) i els valors siguin les descripcions llargues de la infracció en català (*Infraccio_Desc_Llarga_CA*), però només per aquelles infraccions en les que s'hagin retirat punts al conductor (*Punts_A_Retirar > 0*).

<span style="font-family: Courier New; background-color: #82b74b; color: #000000; padding: 3px;">SM</span> **(1.5 punts)**

<div style="background-color: #fcf2f2; border-color: #dfb5b4; border-left: 5px solid #dfb5b4; padding: 0.5em;">
<strong>Solució</strong>
</div>

In [14]:
df.iloc[df["Import_Nominal_?"].idxmax()]#ultilitzant idxmax obtenim en quina posiccio esta el valor maxim de una series i utilitzanr illoc anem a aquest punt

Codi                                                                     1444
Infraccio_Desc_Curta_CA     PORTAR INSTAL.LAT  INHIBIDORS RADAR,CINEMOMETR...
Infraccio_Desc_Curta_ES     LLEVAR INSTALADO INHIBIDORES RADAR,CINEMOMETRO...
Infraccio_Desc_Llarga_CA    Conduir vehicles  que portin  instal.lats inhi...
Infraccio_Desc_Llarga_ES                                                    -
Data_Inici_Vigencia                                                  21/03/22
Article                                                                    77
Normativa                                                                 LSV
Import_Nominal_?                                                         6000
Tipus_Infraccio                                                             M
Punts_A_Retirar                                                             6
Autoritat                         Il.lm./a Sr./a  Primer Tinent/a d'Alcaldia.
Name: 259, dtype: object

In [15]:
def searchbyword(parau):
    temp=df[df["Infraccio_Desc_Curta_ES"].str.contains(parau)]#utilitzant str.contains podem fer filtres utilitzant exprecions regulars
    display(temp)

In [16]:
searchbyword("vehi")

,Codi,Infraccio_Desc_Curta_CA,Infraccio_Desc_Curta_ES,Infraccio_Desc_Llarga_CA,Infraccio_Desc_Llarga_ES,Data_Inici_Vigencia,Article,Normativa,Import_Nominal_?,Tipus_Infraccio,Punts_A_Retirar,Autoritat
525,1778,Llogar vehicle VMP activ econ sense guia,Alquilar vehicul VMP activ econ sin guia,(Grups turistics) Llogar un vehicle de mobilit...,(Grupos turisticos) Alquilar un vehiculo de mo...,20/09/17,71.T 3.1d,OCVV,200,E,0,Il.lm./a Sr./a Regidor/a del Districte
546,1808,No respectar restriccions vehicle mercaderies ...,No respetar restricciones vehiculo mercaderias...,Circular un vehicle en regim de transport de m...,Circular un vehiculo en regimen de transporte ...,01/07/17,71. 5 a,OCVV,200,M,0,Il.lm./a Sr./a Regidor/a del Districte
547,1809,Circular vehicle mercaderies perilloses per un...,Circular vehiculo mercaderias peligrosas por u...,Circular un vehicle en regim de transport de m...,Circular un vehiculo en regimen de transporte ...,01/07/17,71. 5 a,OCVV,200,M,0,Il.lm./a Sr./a Regidor/a del Districte
550,1821,Circular vehicle mercaderis sense autoritzacio...,Circular vehiculo mercaderias sin autorizacion...,Circular un vehicle de transport de mercaderie...,Circular un vehicle de transport de mercaderie...,01/07/17,71. B5,OCVV,500,M,0,Il.lm./a Sr./a Regidor/a del Districte
555,1827,Circular vehicle MMA mes 18t i mes 12 m per Rd...,Circular vehiculo MMA mas 18t y mas 12m por Rd...,Circular vehicle transport mercaderies mercade...,Circular vehicle transport mercaderies mercade...,01/07/17,71. B5,OCVV,500,M,0,Il.lm./a Sr./a Regidor/a del Districte

In [17]:
codis=df[df["Punts_A_Retirar"]>0]["Codi"].to_list()#filtrem les condicions obtenim la clau valor que necesitem com a llistes
descs=df[df["Punts_A_Retirar"]>0]["Infraccio_Desc_Llarga_CA"].to_list()
myDict = { k:v for (k,v) in zip(codis, descs)}  #itererm utilitzant zip per generar el diccionari

In [18]:
myDict

{1213: 'Circular amb exces de velocitat per raons de via.',
 1214: 'Circular amb exces de velocitat per raons de senyal, conductor o vehicle.',
 1215: 'Circular amb exces de velocitat per raons de senyal, conductor o vehicle (mes de 3.500 kg o mes de 9 passatgers).',
 1216: 'Circular amb exces de velocitat per raons de via.',
 1217: 'Circular amb exces de velocitat per raons de senyal, conductor o vehicle.',
 1218: 'Circular amb exces de velocitat per raons de senyal, conductor o vehicle (mes de 3.500 kg o mes de 9 passatgers).',
 1219: 'Circular amb exces de velocitat per raons de via.',
 1220: 'Circular amb exces de velocitat per raons de senyal, conductor o vehicle.',
 1221: 'Circular amb exces de velocitat per raons de senyal, conductor o vehicle (mes de 3.500 kg o mes de 9 passatgers).',
 1222: 'Circular amb exces de velocitat per raons de via.',
 1223: 'Circular amb exces de velocitat per raons de senyal, conductor o vehicle.',
 1224: 'Circular amb exces de velocitat per raons de senyal, conductor o vehicle (mes de 3.500 kg o mes de 9 passatgers).',
 1229: 'Circular amb exces de velocitat per raons de via (mes de 3.500 kg o mes de 9 passatgers).',
 1230: 'Circular amb exces de velocitat per raons de via (mes de 3.500 kg o mes de 9 passatgers).',
 1231: 'Circular amb exces de velocitat per raons de via (mes de 3.500 kg o mes de 9 passatgers).',
 1232: 'Circular amb exces de velocitat per raons de via (mes de 3.500 kg o mes de 9 passatgers).',
 1304: 'Conduir un vehicle de dues rodes de manera manifestament temeraria.',
 1305: 'Conduir un vehicle de manera manifestament temeraria.',
 1306: 'Llencar a la via publica o als seus voltants un objecte que pugui ocasionar un incendi o un accident de circulacio.',
 1327: "Circular amb un menor d'edat d'alcada igual o inferior a 135 centimetres amb un sistema de retencio infantil homologat a l'efecte en el seient davanter del vehicle en suposits no autoritzats",
 1337: 'Circular amb un menor edat  alcada igual o inferior a 135 centimetres sense utilitzar, o no fer-ho de forma adequada, un sistema de retencio infantil homologat a efecte',
 1340: 'Envair el sentit contrari de la circulacio amb perill.',
 1366: "Entaular competencia de velocitat entre vehicles a la via publica o zona d'us public.",
 1386: 'Avancar en revolts, canvis de rasant i en llocs de visibilitat reduida.',
 1395: "Excedir en mes d'un 50% els temps de conduccio establerts en la legislacio sobre transports terrestres.",
 1396: "Minorar en mes d'un 50% els periodes de descans establerts en la legislacio sobre transports terrestres.",
 1401: 'Circular sense utilitzar, degudament cordats, el conductor el cinturo de seguretat.',
 1402: 'No utilitzar el conductor casc de proteccio circulant en ciclomotor.',
 1403: 'No utilitzar el conductor casc de proteccio circulant en motocicleta.',
 1408: 'No utilitzar el conductor casc de proteccio circulant en vehicles de tres rodes o quadricicles, o vehicles especials tipus quad.',
 1444: 'Conduir vehicles  que portin  instal.lats inhibidors de radar o cinemometres  o altres mecanismes per interferir en correcte  funcionament sistemes  vigilancia de transit',
 1446: "No utilitzar el conductor del vehicle que n'ha sortit i ocupa la calcada o el voral de la via, una armilla reflectora de visibilitat alta",
 1474: "Circular per una placa / glorieta / trobada de vies, en sentit contrari de l'estipulat.",
 1485: "Circular en sentit contrari de l'estipulat en una via dividida en mes d'una calcada.",
 1486: "Circular darrere d'un altre vehicle sense mantenir la distancia que li permeti aturar-se, sense col.lisionar, en cas de frenada brusca del que el precedeix",
 1503: "Desobeir els SENYALS i/o les ORDRES D'UN AGENT que regula la circulacio AMB PERILL.",
 1504: "No obeir el conductor d'un ciclomotor o motocicleta el LLUM VERMELL d'un semafor AMB PERILL.",
 1505: "No obeir el conductor d'un vehicle el LLUM VERMELL d'un semafor AMB PERILL.",
 1506: 'No cedir el pas en interseccio regulada amb senyal de CEDIU EL PAS O STOP obligant a la resta de conductor a fer maniobres brusques AMB RISC DE COL.LISIO.',
 1549: 'No utilitzar el conductor casc de proteccio homologat i certificat.',
 1550: "No utilitzar el conductor adequadament el casc de proteccio (especifiqueu-ne l'us inadequat).",
 1576: 'Avancar un vehicle a bicicleta o ciclomotor posant en perill o entorpint a ciclistes que circulen en sentit contrari, inclos arcen',
 1583: 'No respectar la prioritat de pas dels ciclistes amb perill.',
 1584: 'Retrocedir en una via on no estigui autoritzat amb perill.',
 1585: 'Conduir un vehicle utilitzant dispositius de telefonia mobil.',
 1591: 'Conduir un vehicle a motor utilitzant auriculars connectats a aparells receptors o reproductors de so.',
 1620: 'Conduir utilitzant manualment navegadors',
 1650: 'Conduir un vehicle que portin mecanismes de deteccio de radars o cinemometres',
 1686: "Avancar un vehicle a bicicleta o ciclomotor sense deixar una amplada de seguretat d'almenys 1,5 metres",
 1687: 'Conduir un vehicle subjectant amb la ma dispositius de telefonia mobil',
 1688: 'Conduir un vehicle utilitzant dispositius de telefonia mobil mantenint-los ajustats entre el casc de proteccio i el cap de usuari',
 3281: 'Conduir un vehicle. Taxa alcohol en aire expirat superior a 0,15 mg/l, conductor professional, servei public, mercaderies perilloses, transports especials, novells...',
 3282: "Conductor reincident. Conduir un vehicle. Taxa d'alcohol en aire expirat superior a 0,15 mg/l, conductor professional, servei public, mercaderies perilloses, transports especials, novells",
 3284: "Conduir un vehicle. Taxa d'alcohol en aire expirat superior a 0,25 mg/l",
 3285: "Conductor reincident. Conduir un vehicle. Taxa d'alcohol en aire expirat superior a 0,25 mg/l",
 3287: "Conduir un vehicle. Taxa d'alcohol en aire expirat superior a 0,30 mg/l, conductor professional, servei public, mercaderies perilloses, transports especials, novells...",
 3288: "Conductor reincident. Conduir un vehicle. Taxa d'alcohol en aire expirat superior a 0,30 mg/l, conductor professional, servei public, mercaderies perilloses, transports especials, novells",
 3290: "Conduir un vehicle. Taxa d'alcohol en aire expirat superior a 0,50 mg/l",
 3291: "Conductor reincident. Conduir un vehicle. Taxa d'alcohol en aire expirat superior a 0,50 mg/l",
 3293: "No sotmetre's a les proves de deteccio alcoholica, el conductor d'un vehicle",
 3296: "Conduir un vehicle amb presencia de drogues a l'organisme",
 3299: "No sotmetre's, el conductor un vehicle  a les proves per a la deteccio de drogues a organisme"}

## Exercici 6

En aquest exercici practicareu expressions regulars, per això us demanem:

6.1. Utilitzeu expressions regulars per trobar totes les infraccions la descripció llarga en català (*Infraccio_Desc_Llarga_CA*) mencioni qualsevol forma de la paraula 'velocitat' (per exemple, 'velocitat', 'velocitats', etc.). Mostreu les files que corresponen a aquestes infraccions.

6.2. Utilitzeu expressions regulars per trobar totes les infraccions la descripció curta en espanyol (*Infraccio_Desc_Curta_ES*) mencioni algun número, sense importar el seu format (per exemple, 100, 2000, 10.000, etc.). Mostreu les files corresponents a aquestes infraccions.

6.3. Utilitzeu expressions regulars per trobar totes les infraccions la descripció curta en espanyol (*Infraccio_Desc_Curta_ES*) mencioni termes: ciclistes, arcen, cruïlla, estacionar. Mostreu les files corresponents a aquestes infraccions.

<span style="font-family: Courier New; background-color: #82b74b; color: #000000; padding: 3px;">SM</span> **(1.5 punts)**

<div style="background-color: #fcf2f2; border-color: #dfb5b4; border-left: 5px solid #dfb5b4; padding: 0.5em;">
<strong>Solució</strong>
</div>

In [19]:
df[df["Infraccio_Desc_Llarga_CA"].str.contains("velocitat",na=False, case=False)]#utilitzem str.contains per fer explresions rergulars en els tres casos

,Codi,Infraccio_Desc_Curta_CA,Infraccio_Desc_Curta_ES,Infraccio_Desc_Llarga_CA,Infraccio_Desc_Llarga_ES,Data_Inici_Vigencia,Article,Normativa,Import_Nominal_?,Tipus_Infraccio,Punts_A_Retirar,Autoritat
122,1140,NO REDUIR VELOCITAT CARRER UNIC CARRIL,NO REDUCIR VELOCIDAD CALLE DE UN CARRIL,No reduir la velocitat en carrers d'un sol car...,-,15/02/17,11. 2,OCVV,40,M,0,Il.lm./a Sr./a Regidor/a del Districte
123,1141,NO REDUIR VELOC EN CARRER SENSE VORERES,NO REDUCIR VELOCIDAD EN CALLE SIN ACERAS,No reduir la velocitat en carrers sense vorera.,-,15/02/17,11. 2,OCVV,40,M,0,Il.lm./a Sr./a Regidor/a del Districte
124,1142,NO REDUIR VELOC SITUACIO AFLUENCIA VIAN,NO REDUCIR VELOC SITUAC AFLUENCIA PEATON,No reduir la velocitat en una situacio de gran...,-,15/02/17,11. 2,OCVV,40,M,0,Il.lm./a Sr./a Regidor/a del Districte
125,1143,NO REDUIR VELOCITAT PLUJA/NEU/POLS/FUM,NO REDUCIR VELOC LLUVIA/NIEVE/POLVO/HUMO,"No reduir la velocitat en cas de pluja, neu, p...",-,15/02/17,11. 3,OCVV,40,M,0,Il.lm./a Sr./a Regidor/a del Districte
126,1144,NO REDUIR VELOCIT EN MAL ESTAT PAVIMENT,NO REDUCIR VELOC EN MAL ESTADO PAVIMENTO,No reduir la velocitat en cas de mal estat del...,-,15/02/17,11. 3,OCVV,40,M,0,Il.lm./a Sr./a Regidor/a del Districte
127,1145,NO REDUIR VELOCITAT EN ESTRETOR DE VIA,NO REDUCIR VELOCIDAD EN ESTRECHEZ DE VIA,No reduir la velocitat a causa de l'estretor d...,-,15/02/17,11. 3,OCVV,40,M,0,Il.lm./a Sr./a Regidor/a del Districte
128,1153,NO REDUIR VELOCITAT EN CARRERS D'UNA ZONA 30,NO REDUCIR VELOCIDAD EN CALLES DE UNA ZONA 30,No reduir la velocitat en carrers d'una zona 30.,-,03/01/00,11. 2,OCVV,90,M,0,Il.lm./a Sr./a Regidor/a del Districte
129,1154,NO REDUIR VELOCITAT EN CARRER DE PRIORITAT INV...,NO REDUCIR VELOCIDAD EN CALLE DE PRIORIDAD INV...,No reduir la velocitat en carrers de prioritat...,-,03/01/00,11. 3,OCVV,90,M,0,Il.lm./a Sr./a Regidor/a del Districte
150,1210,CIRCULA AMB EXCES DE VELOCITAT PER RAO DE VIA,CIRCULA CON EXCESO DE VELOCIDAD POR RAZON DE VIA,Circular amb exces de velocitat per raons de via.,-,25/11/09,50. 1,RGC,100,M,0,Il.lm./a Sr./a Regidor/a del Districte
151,1211,SUPERAR LIMIT VELOCITAT SENYAL ESPECIFIC,SUPERAR LIMITE VELOCIDAD SENAL ESPECIFIC,Circular amb exces de velocitat per raons de s...,-,25/11/09,52. 1,RGC,100,M,0,Il.lm./a Sr./a Regidor/a del Districte
152,1212,SUPERAR LIMIT VELOCITAT VEHICLE ESPECIAL,SUPERAR LIMITE VELOCIDAD VEHIC ESPECIAL,Circular amb exces de velocitat per raons de s...,-,25/11/09,52. 1,RGC,100,M,0,Il.lm./a Sr./a Regidor/a del Districte
153,1213,SUPERAR LIMIT VELOCITAT NORMA GENERAL,SUPERAR LIMITE VELOCIDAD NORMA GENERAL,Circular amb exces de velocitat per raons de via.,-,21/03/22,50. 1,RGC,300,M,2,Il.lm./a Sr./a Regidor/a de Mobilitat
154,1214,SUPERAR LIMIT VELOCITAT SENYAL ESPECIFIC,SUPERAR LIMITE VELOCIDAD SENAL ESPECIFIC,Circular amb exces de velocitat per raons de s...,-,21/03/22,52. 1,RGC,300,M,2,Il.lm./a Sr./a Regidor/a de Mobilitat
155,1215,SUPERAR LIMIT VELOCITAT VEHICLE ESPECIAL,SUPERAR LIMITE VELOCIDAD VEHIC ESPECIAL,Circular amb exces de velocitat per raons de s...,-,21/03/22,52. 1,RGC,300,M,2,Il.lm./a Sr./a Regidor/a de Mobilitat
156,1216,SUPERAR LIMIT VELOCITAT NORMA GENERAL,SUPERAR LIMITE VELOCIDAD NORMA GENERAL,Circular amb exces de velocitat per raons de via.,-,21/03/22,50. 1,RGC,400,M,4,Il.lm./a Sr./a Regidor/a de Mobilitat
157,1217,SUPERAR LIMIT VELOCITAT SENYAL ESPECIFIC,SUPERAR LIMITE VELOCIDAD SENAL ESPECIFIC,Circular amb exces de velocitat per raons de s...,-,21/03/22,52. 1,RGC,400,M,4,Il.lm./a Sr./a Regidor/a de Mobilitat
158,1218,SUPERAR LIMIT VELOCITAT VEHICLE ESPECIAL,SUPERAR LIMITE VELOCIDAD VEHIC ESPECIAL,Circular amb exces de velocitat per raons de s...,-,21/03/22,52. 1,RGC,400,M,4,Il.lm./a Sr./a Regidor/a de Mobilitat
159,1219,EXCES VELOCITAT PER RAO DE VIA,EXCESO DE VELOCIDAD POR RAZON DE VIA,Circular amb exces de velocitat per raons de via.,-,21/03/22,50. 1,RGC,500,M,6,Il.lm./a Sr./a Regidor/a de Mobilitat
160,1220,EXCES VELOCITAT PER SENYAL/CONDUCT/VEHIC,EXCESO VELOCIDAD POR SENAL/CONDUCT/VEHIC,Circular amb exces de velocitat per raons de s...,-,21/03/22,52. 1,RGC,500,M,6,Il.lm./a Sr./a Regidor/a de Mobilitat
161,1221,EXCES VELOCITAT PER SENYAL/CONDUCT/VEHIC,EXCESO VELOCIDAD POR SENAL/CONDUCT/VEHIC,Circular amb exces de velocitat per raons de s...,-,21/03/22,52. 1,RGC,500,M,6,Il.lm./a Sr./a Regidor/a de Mobilitat
162,1222,EXCES VELOCITAT PER RAO DE VIA,EXCESO VELOCIDAD POR RAZON DE VIA,Circular amb exces de velocitat per raons de via.,-,21/03/22,50. 1,RGC,600,M,6,Il.lm./a Sr./a Regidor/a de Mobilitat
163,1223,EXCES VELOCITAT PER SENYAL/CONDUCT/VEHIC,EXCESO VELOCIDAD POR SENAL/CONDUCT/VEHIC,Circular amb exces de velocitat per raons de s...,-,21/03/22,52. 1,RGC,600,M,6,Il.lm./a Sr./a Regidor/a de Mobilitat
164,1224,EXCES VELOCITAT PER SENYAL/CONDUCT/VEHIC,EXCESO VELOCIDAD POR SENAL/CONDUCT/VEHIC,Circular amb exces de velocitat per raons de s...,-,21/03/22,52. 1,RGC,600,M,6,Il.lm./a Sr./a Regidor/a de Mobilitat
165,1228,SUPERAR LIMIT VELOCITAT VEHICLE ESPECIAL,SUPERAR LIMITE VELOCIDAD VEHIC ESPECIAL,Circular amb exces de velocitat per raons de v...,-,25/11/09,50. 1,RGC,100,M,0,Il.lm./a Sr./a Regidor/a del Districte
166,1229,SUPERAR LIMIT VELOCITAT VEHICLE ESPECIAL,SUPERAR LIMITE VELOCIDAD VEHIC ESPECIAL,Circular amb exces de velocitat per raons de v...,-,21/03/22,50. 1,RGC,300,M,2,Il.lm./a Sr./a Regidor/a de Mobilitat
167,1230,SUPERAR LIMIT VELOCITAT VEHICLE ESPECIAL,SUPERAR LIMITE VELOCIDAD VEHIC ESPECIAL,Circular amb exces de velocitat per raons de v...,-,21/03/22,50. 1,RGC,400,M,4,Il.lm./a Sr./a Regidor/a de Mobilitat
168,1231,EXCES VELOCITAT PER RAO DE VIA,EXCESO VELOCIDAD POR RAZON DE VIA,Circular amb exces de velocitat per raons de v...,-,21/03/22,50. 1,RGC,500,M,6,Il.lm./a Sr./a Regidor/a de Mobilitat
169,1232,EXCES VELOCITAT PER SENYAL/CONDUCT/VEHIC,EXCESO VELOCIDAD POR SENAL/CONDUCT/VEHIC,Circular amb exces de velocitat per raons de v...,-,21/03/22,50. 1,RGC,600,M,6,Il.lm./a Sr./a Regidor/a de Mobilitat
171,1301,CIRC PATI O SIMIL A MAJOR VELOC VIANANTS,CIRC PATIN O SIMIL A MAYOR VELOC PEATON,"Circular en patinet, monopati o aparell simila...",-,01/01/02,121. 4,RGC,30,M,0,Il.lm./a Sr./a Regidor/a del Districte
207,1364,CIRC VELOC INFERIOR A MINIMA ESTABLERTA,CIRC VELOC INFERIOR A MINIMA ESTABLECIDA,Circular a velocitat anormalment reduida sense...,-,25/05/10,49. 1,RGC,200,M,0,Il.lm./a Sr./a Regidor/a del Districte
208,1365,REDU BRUSC VELOC NO EXISTIN PERILL INMIN,REDU BRUSC VELOC NO EXIST PELIGRO INMIN,Reduccio brusca i imprudent de la velocitat se...,-,25/05/10,53. 1,RGC,200,M,0,Il.lm./a Sr./a Regidor/a del Districte
209,1366,FER COMPETENCIA VELOCITAT ENTRE VEHICLES SENSE...,CELEBRAR COMPETENCIA VELOCIDAD ENTRE VEHICULOS...,Entaular competencia de velocitat entre vehicl...,-,31/01/16,55. 2,RGC,500,M,6,Il.lm./a Sr./a Regidor/a de Mobilitat
314,1515,NO MODER VELOC EXIGINT-HO CIRCUMSTANCIES,NO MODER VELOC EXIGIENDOLO CIRCUNSTANCIA,Circular amb un vehicle sense moderar la veloc...,-,25/05/10,46. 1,RGC,200,M,0,Il.lm./a Sr./a Regidor/a del Districte
385,1595,CIRCULAR BICICLETA A VELOCITAT INADEQUADA EN C...,CIRCULAR BICICLIETA A VELOCIDAD INADECUADAEN C...,Circular en bicicleta pel carril bici a una ve...,-,08/01/19,10,OCVV,100,M,0,Il.lm./a Sr./a Regidor/a del Districte
389,1605,NO RESPECTAR VEHICLE MOTOR DISTANCIA SEGURETAT...,NO RESPETAR VEHICULO MOTOR DISTANCIA SEGURIDAD...,Circular un vehicle darrera d'una bicicleta se...,-,08/01/19,71.T 2,OCVV,100,M,0,Il.lm./a Sr./a Regidor/a del Districte
461,1708,TRAVESSAR PAS VIANANTS EN BICICLETA AFECTANT S...,CRUZAR PASO PEATONES EN BICICLETA AFECTANDO SE...,Circular en bicicleta sense reduir la velocita...,-,08/01/19,71.T 2,OCVV,100,M,0,Il.lm./a Sr./a Regidor/a del Districte
484,1735,Circular VMP/cicle mes 2r no adequant la veloc...,Circular VMP/ciclo mas 2r no adecua la velocid...,Circular amb un vehicle de mobilitat personal ...,Circular con una vehiculo de movilidad persona...,01/07/17,71.T 3,OCVV,100,M,0,Il.lm./a Sr./a Regidor/a del Districte
490,1742,VMP/cicle mes 2r A/C2 platafor unica vianant a...,VMP/ciclo mas 2r A/C2 platafor unica peaton co...,Circular amb un vehicle de mobilitat personal ...,Circular con un vehiculo de movilidad personal...,01/07/17,71.T 3.1a,OCVV,200,M,0,Il.lm./a Sr./a Regidor/a del Districte
491,1743,VMP/cicle mes 2r A/B/C1/C2 sense respectar pa...,VMP/ciclo mas 2r A/B/C1/C2 sin respetar paso ...,Circular amb un vehicle de mobilitat personal ...,Circular con un vehiculo de movilidad personal...,01/07/17,71.T 3,OCVV,100,M,0,Il.lm./a Sr./a Regidor/a del Districte
492,1744,Circul VMP/cicle mes 2r A/B/C1/C2 platafor uni...,Circul VMP/ciclo mas 2r A/B/C1/C2 platafor uni...,Circular amb un vehicle de mobilitat personal ...,circular con un vehiculo de movilidad personal...,01/07/17,71.T 3.1a,OCVV,200,M,0,Il.lm./a Sr./a Regidor/a del Districte
494,1746,VMP/cicle mes 2r B/C1/C2 per carrilbici no seg...,VMP/cicle mas 2r B/C1/C2 por carrilbici no seg...,Circular amb un vehicle de mobilitat personal ...,Circular con un vehiculo de movilidad personal...,01/07/17,71.T 3.1a,OCVV,200,M,0,Il.lm./a Sr./a Regidor/a del Districte
495,1747,VMP/cicle mes 2r A/B/C1/C2 per carril bici seg...,VMP/ciclo mas 2r A/B/C1/C2 por carril bici seg...,Circular amb un vehicle de mobilitat personal ...,Circular con un vehiculo de movilidad personal...,01/07/17,71.T 3.1a,OCVV,200,M,0,Il.lm./a Sr./a Regidor/a del Districte
496,1748,Circul VMP/cicle mes 2r A/B/C1/C2 calcad zona ...,Circul VMP/ciclo mas 2r A/B/C1/C2 calzada zona...,Circular amb un vehicle de mobilitat personal ...,Circular con un vehiculo de movilidad personal...,01/07/17,71.T 3.1a,OCVV,200,M,0,Il.lm./a Sr./a Regidor/a del Districte
500,1752,Circul cicle mes 2r C1/C2 per zona prohibida v...,Circul ciclo mas 2r C1/C2 por zona prohibida v...,Circular amb un cicle de mes de dues rodes del...,Circular con un ciclo de mas de dos ruedas del...,01/07/17,71.T 3.1a,OCVV,200,M,0,Il.lm./a Sr./a Regidor/a del Districte

In [20]:
df[df["Infraccio_Desc_Curta_ES"].str.contains("\d",na=False)]

,Codi,Infraccio_Desc_Curta_CA,Infraccio_Desc_Curta_ES,Infraccio_Desc_Llarga_CA,Infraccio_Desc_Llarga_ES,Data_Inici_Vigencia,Article,Normativa,Import_Nominal_?,Tipus_Infraccio,Punts_A_Retirar,Autoritat
12,1011,PARAR CARR/PLAC S/VORERES MENYS 1M FACAN,PARAR CALL/PLAZ S/ACERAS MENOS 1M FACHAD,Parar en carrers o places sense vorera sense a...,-,01/01/02,70.2 P,OCVV,30,E,0,Il.lm./a Sr./a Regidor/a del Districte
47,1049,ESTAC DIST INFER 5 M ALINEACIO VORADA CARRER T...,ESTAC DIST INFER 5 M ALINEACIO BORDILLO CALLE ...,Estacionar a menys de 5 m de l'alineacio de la...,-,25/05/10,70.2 D,OCVV,60,E,0,Il.lm./a Sr./a Regidor/a del Districte
60,1062,ESTAC MES 8 DIES CONSECUT UN MATEIX LLOC,ESTAC MAS 8 DIAS CONSECUTIV MISMO LUGAR,Estacionar mes de 8 dies consecutius en un mat...,-,25/05/10,70.2 Q,OCVV,60,E,0,Il.lm./a Sr./a Regidor/a del Districte
71,1080,ESTAC MOTO/CICLOMOT VORERA INFERIOR A 3M,ESTAC MOTO/CICLOMOT ACERA INFERIOR A 3 M,Estacionar una motocicleta o un ciclomotor en ...,-,25/05/10,70.2 L,OCVV,50,E,0,Il.lm./a Sr./a Regidor/a del Districte
72,1081,ESTAC MOTO/CICLOM MES 50 CM LINEA VORERA,ESTAC MOTO/CICLOM MAS 50 CM LINEA ACERA,Estacionar una motocicleta o un ciclomotor a m...,-,25/05/10,70.2 L,OCVV,50,E,0,Il.lm./a Sr./a Regidor/a del Districte
...,...,...,...,...,...,...,...,...,...,...,...,...
603,3389,"CONDUCTOR MENOR NOVELL TAXA ALCOHOL FINS 0,15 ...","CONDUCTOR MENOR NOVEL TAXA ALCOHOL HASTA 0,15 ...",Conduir un menor edat un vehicle. Taxa alcohol...,Conducir un menor edad un vehiculo. Tasa alcoh...,21/03/22,14. 1,LSV,500,M,0,Il.lm./a Sr./a Regidor/a del Districte
604,3390,CONDUCTOR MENOR NOVELL REINCIDENT TAXA ALCOHOL...,CONDUCTOR MENOR NOVEL REINCIDENTE TAXA ALCOHOL...,Conductor reincident. Conduir un menor edat un...,Conductor reincidente. Conducir un menor edad ...,21/03/22,14. 1,LSV,1000,M,0,Il.lm./a Sr./a Regidor/a del Districte
605,3391,"CONDUCTOR MENOR TAXA ALCOHOL FINS 0,25 MG/L SE...","CONDUCTOR MENOR TAXA ALCOHOL HASTA 0,25 MG/L S...",Conduir un menor edat un vehicle. Taxa alcohol...,Conducir un menor edad un vehiculo. Tasa alcoh...,21/03/22,14. 1,LSV,500,M,0,Il.lm./a Sr./a Regidor/a del Districte
606,3392,CONDUCTOR MENOR REINCIDENT TAXA ALCOHOL FINS 0...,CONDUCTOR MENOR REINCIDENTE TAXA ALCOHOL HASTA...,Conductor reincident. Conduir un menor edat un...,Conductor reincidente. Conducir un menor edad ...,21/03/22,14. 1,LSV,1000,M,0,Il.lm./a Sr./a Regidor/a del Districte
607,3393,"CONDUCT MENOR CICLE/VMP/CICLE 2RODES, TAXA ALC...","CONDUC MENOR CICLO/ MAS 2 RUEDA/VMP, TAXA ALCO...",Conduir un menor edat una bicicleta / vehicle ...,Conducir un menor edad una bicicleta / vehicul...,21/03/22,14. 1,LSV,500,M,0,Il.lm./a Sr./a Regidor/a del Districte

In [21]:
df[df["Infraccio_Desc_Curta_ES"].str.contains("ciclistes|arcen|cruïlla|estacionar",na=False, case=False)]

,Codi,Infraccio_Desc_Curta_CA,Infraccio_Desc_Curta_ES,Infraccio_Desc_Llarga_CA,Infraccio_Desc_Llarga_ES,Data_Inici_Vigencia,Article,Normativa,Import_Nominal_?,Tipus_Infraccio,Punts_A_Retirar,Autoritat
17,1016,PARAR-SE EN VORERA O ANDANA,PARARSE EN ACERA O ARCEN,Parar a la vorera o el voral.,-,01/01/02,70.2 L,OCVV,60,E,0,Il.lm./a Sr./a Regidor/a del Districte
28,1029,ESTACIONAR EN CARRIL BICICLETES,ESTACIONAR EN CARRIL BICICLETAS,Estacionar en un carril bicicleta,Estacionar en un carril bicicleta,21/03/22,76. D,LSV,200,E,0,Il.lm./a Sr./a Regidor/a del Districte
35,1036,ESTACIONAR EN PAS DE CICLISTES,ESTACIONAR EN PASO DE CICLISTAS,Estacionar en passos per a ciclistes.,Estacionar en pasos para ciclistas,21/03/22,76. D,LSV,200,E,0,Il.lm./a Sr./a Regidor/a del Districte
36,1037,ESTACIONAR EN PAS PER A VIANANTS,ESTACIONAR EN PASO PARA PEATONES,Estacionar en passos de vianants.,-,25/05/10,70.2 B,OCVV,90,E,0,Il.lm./a Sr./a Regidor/a del Districte
38,1039,ESTACIONAR EN CARRIL BUS,ESTACIONAR EN CARRIL BUS,Estacionar en un carril BUS.,-,01/01/06,70.2 G,OCVV,200,E,0,Il.lm./a Sr./a Regidor/a del Districte
39,1040,ESTACIONAR EN PARADA TRANSPORT PUBLIC,ESTACIONAR EN PARADA TRANSPORTE PUBLICO,Estacionar en parades de transport public.,-,25/05/10,70.2 H,OCVV,200,E,0,Il.lm./a Sr./a Regidor/a del Districte
40,1041,ESTACIONAR A LES ZONES RESERVADES,ESTACIONAR EN ZONAS RESERVADAS,Estacionar en una zona reservada,-,25/05/10,70.2 C,OCVV,90,E,0,Il.lm./a Sr./a Regidor/a del Districte
41,1042,ESTACIONAR EN CRUILLA O INTERSECCIO,ESTACIONAR EN CRUCE O INTERSECCION,Estacionar en cruilles o interseccions.,-,25/05/10,70.2 D,OCVV,90,E,0,Il.lm./a Sr./a Regidor/a del Districte
45,1047,ESTACIONAR EN PLENA CALCADA,ESTACIONAR EN PLENA CALZADA,Estacionar en plena calcada.,-,25/05/10,70.2 F,OCVV,90,E,0,Il.lm./a Sr./a Regidor/a del Districte
48,1050,ESTACIONAR EN VORERA,ESTACIONAR EN ACERA,Estacionar a la vorera,-,25/05/10,70.2 L,OCVV,90,E,0,Il.lm./a Sr./a Regidor/a del Districte
49,1051,ESTACIONAR EN ANDANA/PARTERRE/REFUGI,ESTACIONAR EN ANDEN/PARTERRE/REFUGIO,"Estacionar en una andana, en un parterre o en ...",-,25/05/10,70.2 L,OCVV,90,E,0,Il.lm./a Sr./a Regidor/a del Districte
50,1052,ESTACIONAR EN PASSEIG CENTRAL O LATERAL,ESTACIONAR EN PASEO CENTRAL O LATERAL,Estacionar en un passeig central o lateral.,-,25/05/10,70.2 L,OCVV,60,E,0,Il.lm./a Sr./a Regidor/a del Districte
52,1054,ESTACIONAR AL COSTAT D ANDANA O REFUGI,ESTACIONAR AL LADO DE ANDEN O REFUGIO,Estacionar al costat d'andanes o refugis.,-,25/05/10,70.2 Q,OCVV,60,E,0,Il.lm./a Sr./a Regidor/a del Districte
97,1110,ESTACIONAR VEHICLE PER VENDA O LLOGUER,ESTACIONAR VEHICULO PARA VENTA/ALQUILER,Estacionar vehicles a la via publica per a la ...,-,25/05/10,29. 21,OCVV,90,E,0,Il.lm./a Sr./a Regidor/a del Districte
98,1111,ESTACIONAR VEHICLE AMB FI PUBLICITARI,ESTACIONAR VEHICULO CON FIN PUBLICITARIO,Estacionar vehicles a la via publica amb final...,-,25/05/10,29. 21,OCVV,90,E,0,Il.lm./a Sr./a Regidor/a del Districte
100,1114,ESTACIONAR EN ZONA BLAVA SENSE ACREDITACIO VALIDA,ESTACIONAR EN ZONA AZUL SIN ACREDITACION VALIDA,(Zona Blava) Fer us d'una targeta no expedida ...,-,03/01/00,33. 1,OCVV,50,E,0,Il.lm./a Sr./a Regidor/a del Districte
101,1115,ESTACIONAR CARREGA/DESCARREGA SENSE ACREDITACI...,ESTACIONAR CARGA/DESCARGA SIN ACREDITACION VALIDA,(Zona carrega/descarrega) Fer us d'una targeta...,-,03/01/00,33. 1,OCVV,60,E,0,Il.lm./a Sr./a Regidor/a del Districte
102,1116,ESTACIONAR EN ZONA DISCAPACITATS SENSE ACREDIT...,ESTACIONAR EN ZONA DISCAPACITADOS SIN ACREDITA...,(Zona reserv. pers. mobilitat reduida) Fer us ...,-,03/01/00,33. 1,OCVV,100,E,0,Il.lm./a Sr./a Regidor/a del Districte
103,1117,ESTACIONAR ZONA RESERVADA SENSE ACREDITACIO VA...,ESTACIONAR ZONA RESERVADA SIN ACREDITACION VALIDA,(Zona reservada altres usuaris) Fer us d'una t...,-,03/01/00,33. 1,OCVV,90,E,0,Il.lm./a Sr./a Regidor/a del Districte
109,1125,ESTACIONAR IMPEDINT LA CIRCULACIO,ESTACIONAR IMPIDIENDO LA CIRCULACION,Estacionar de manera que no permeti la circula...,-,25/05/10,70.2 Q,OCVV,90,E,0,Il.lm./a Sr./a Regidor/a del Districte
112,1128,ESTACIONAR EN ANDANA,ESTACIONAR EN ANDEN,Estacionar al voral.,-,25/05/10,70.2 L,OCVV,90,E,0,Il.lm./a Sr./a Regidor/a del Districte
130,1156,ESTACIONAR EN REBAIX DE VORERA PER A PERSONA D...,ESTACIONAR EN REBAJE DE ACEERA PARA PERSONA DI...,Estacionar en els rebaixos de les voreres per ...,-,25/05/10,70.2 B,OCVV,90,E,0,Il.lm./a Sr./a Regidor/a del Districte
132,1158,ESTACIONAR MOTO/CICLOMOT VORERA DAVANT ZONA RE...,ESTACIONAR MOTO/CICLOMOT ACERA DELANTE ZONA RE...,Estacionar una motocicleta o un ciclomotor en ...,-,25/05/10,70.2 L,OCVV,50,E,0,Il.lm./a Sr./a Regidor/a del Districte
138,1165,ESTACIONA MOTO/CICLOM EN VORERA SENSE ESPAI 3 ...,ESTACIONAR MOTO/CICLOM EN ACERA SIN ESPACIO 3 ...,Estacionar una motocicleta o un ciclomotor sen...,-,25/05/10,70.2 L,OCVV,50,E,0,Il.lm./a Sr./a Regidor/a del Districte
139,1168,ESTACIONAR EN EL SENTIT CONTRARI DE LA CIRCULACIO,ESTACIONAR EN EL SENTIDO CONTRARIO DE LA CIRCU...,Estacionar en el sentit contrari de la circulacio,Estacionar en el sentido contrario de la circu...,22/04/21,90. 2,RGC,200,E,0,Il.lm./a Sr./a Regidor/a del Districte
143,1183,ESTACIONAR UN AUTOCAR ON HO PROHIBEIX EL SENYA...,ESTACIONAR AUTOCAR DONDE LO PROHIBE LA SENAL C...,Estacionar autocar on ho prohibeix el senyal c...,-,03/01/00,70.2 O,OCVV,100,E,0,Il.lm./a Sr./a Regidor/a del Districte
145,1185,ESTACIONAR EN ZONA DE RECARREGA DE VEHICLES EL...,ESTACIONAR EN ZONA DE RECARGA DE VEHICULOS ELE...,Estacionar en una zona de recarrega de vehicle...,-,03/01/00,70.2 C,OCVV,90,E,0,Il.lm./a Sr./a Regidor/a del Districte
146,1186,ESTACIONAR VEHICLE ELECTRIC EN ZONA RECARREGA ...,ESTACIONAR VEHICULO ELECTRICO EN Z RECARGA EXC...,Estacionar vehicle electric en zona de recarre...,-,03/01/00,70.2 C,OCVV,90,E,0,Il.lm./a Sr./a Regidor/a del Districte
147,1187,ESTACIONAR AUTOCAR ON HO PROHIBEIX SENYAL CORR...,ESTACIONAR AUTOCAR DONDE PROHIBE SENYAL CORRES...,Estacionar autocar on ho prohibeix el senyal c...,Estacionar autocar donde lo prohibe la senal c...,16/06/22,70.2 O,OCVV,100,E,0,Il.lm./a Sr./a Regidor/a del Districte
148,1188,ESTACIONAR VEH ELECTRIC ZONA RECARREGA RESERV ...,ESTACIONAR VEH ELECTRICO ZONA RECARGA RESERV P...,Estacionar vehicle electric en zona de recarre...,Estacionar vehiculo electrico en zona de recar...,07/01/19,70.2 C,OCVV,90,E,0,Il.lm./a Sr./a Regidor/a del Districte
149,1189,ESTACIONAR AUTOCAR ZONA RESERVADA AUTOCAR SENS...,ESTACIONAR AUTOCAR ZONA RESERVADA AUTOCAR SIN ...,Estacionar autocar en una zona habilitada per ...,Estacionar autocar en una zona habilitada para...,13/06/22,70.2 I,OCVV,100,E,0,Il.lm./a Sr./a Regidor/a del Districte
202,1341,CIRC ARCEN VEHIC NO AUTORIZ SENSE EMERG,CIRC ARCEN VEHIC NO AUTORIZ SIN EMERGENC,Circular pel voral un vehicle no autoritzat se...,-,21/05/03,30. 1,RGC,90,M,0,Il.lm./a Sr./a Regidor/a del Districte
311,1512,NO RESPEC PRIORITAT VIANANTS EN ANDANES,NO RESPETAR PRIORIDAD PEATONES EN ARCEN,No respectar la prioritat dels vianants als vo...,-,25/05/10,65.1 C,RGC,200,M,0,Il.lm./a Sr./a Regidor/a del Districte
377,1587,ESTACIONAR AMB RISC A CIRCULACIO/VIANANTS AMB ...,ESTACIONAR CON RIESGO A CIRCULACION/PEATONES C...,Estacionar de manera que constitueixi risc a l...,-,25/05/10,94. 2,RGC,200,E,0,Il.lm./a Sr./a Regidor/a del Districte
379,1589,ESTACIONA CARRIL T PUBLIC GREU PERTORBACIO/RIS...,ESTACIONAR CARRIL T PUBLIC GRAVE PERTURBAC/RIE...,Estacionar en carril destinat al transport pub...,-,25/05/10,94. 2,RGC,200,E,0,Il.lm./a Sr./a Regidor/a del Districte
393,1609,ESTACIONAR BICICLETA EN LLOC NO AUTORITZAT,ESTACIONAR BICICLETA EN LUGAR NO AUTORIZADO,Estacionar una bicicleta i lligar-la en llocs ...,-,08/01/19,71.T 2,OCVV,100,E,0,Il.lm./a Sr./a Regidor/a del Districte
466,1713,ESTACIONAR BICICLETA DAVANT ZONES ESTACIONAMEN...,ESTACIONAR BICICLETA DELANTE ZONAS APARCAMIENT...,Estacionar una bicicleta davant de zones on hi...,-,08/01/19,71.T 2,OCVV,100,E,0,Il.lm./a Sr./a Regidor/a del Districte
467,1714,ESTACIONAR BICICLETA A LA VORERA IMPEDINT PAS ...,ESTACIONAR BICICLETA EN ACERA IMPIDIENDO PASO ...,Estacionar una bicicleta a la vorera quan s'im...,-,08/01/19,71.T 2,OCVV,100,E,0,Il.lm./a Sr./a Regidor/a del Districte
470,1717,PARAR O ESTACIONAR VEHICLE MOTOR A CARRILS/VIE...,PARAR O ESTACIONAR VEHICULO MOTOR EN CARRILS/V...,"Parar, o estacionar un vehicle als carrils bic...","Parar, o estacionar un vehiculo a los carriles...",22/03/22,76. D,LSV,200,E,0,Il.lm./a Sr./a Regidor/a del Districte
521,1774,Estacionar VMP comercial A/B a llocs reservats,Estacionar VMP comercial A/B lugar reservado,Estacionar vehicle mobilitat personal (VMP) d'...,Estacionar vehicle mobilitat personal (VMP) d'...,01/07/17,71.T 3,OCVV,100,E,0,Il.lm./a Sr./a Regidor/a del Districte
536,1793,ESTACIONAR LLOCS NO HABILITATS CICLE 2R C1 O C2,ESTACIONAR LUGAR NO AUTORIZADO CICLO 2R C1 O C2,Estacionar un cicle de mes de dues rodes del t...,Estacionar un ciclo de mas de dos ruedas del t...,08/01/19,71.T 3,OCVV,100,E,0,Il.lm./a Sr./a Regidor/a del Districte
539,1796,ESTACIONAR VMP TIPUS A/B A LLOCS RESERVATS,ESTACIONAR VMP TIPO A/B LUGAR RESERVADO,Estacionar vehicle mobilitat personal (VMP)del...,Estacionar vehicle mobilitat personal (VMP)del...,08/01/19,71.T 3,OCVV,100,E,0,Il.lm./a Sr./a Regidor/a del Districte
540,1797,ESTACIONAR VMP TIPUS A/B IMPEDINT EL PAS VIANA,ESTACIONAR VMP TIPO A/B IMPEDIENDO PASO PEATON,Estacionar vehicle mobilitat personal (VMP) de...,Estacionar vehicle mobilitat personal (VMP) de...,08/01/19,71.T 3,OCVV,100,E,0,Il.lm./a Sr./a Regidor/a del Districte

## Exercici 7. Projecte

**Exercici: Gestió d'una llista d'infraccions pendents**

**Enunciat**:

Creeu un programa que mantingui una llista d'infraccions pendents de tramitar. Només contindrà codis d'infracció (1 columna).

* Comenceu amb una llista buida.
* Demaneu a l'usuari que afegeixi infraccions (codis d'infracció) a la llista.
* Permeteu a l'usuari treure una infracció de la llista si ja ha estat trametuda.
* Mostreu la llista d'infraccions pendents després de cada operació.

**Detalls**:

* El programa oferirà (demanarà a l'usuari) 3 opcions: Afegir infracció, eliminar infracció i sortir.
* Si escull l'opció Afegir, el programa ha de permetre afegir múltiples infraccions fins que l'usuari decideixi acabar.
* Si escull l'opció Eliminar, l'usuari pot eliminar una infracció especificant el seu codi. Si el codi d'infracció a eliminar no està a la llista, el programa ha de notificar a l'usuari.
* Si escull l'opció Sortir, el programa finalitza.

<span style="font-family: Courier New; background-color: #82b74b; color: #000000; padding: 3px;">SM</span> **(1.5 punts)**

In [22]:
def app():
    infr=[]#la llista de infraccions
    a=True #comprobador si hem de parar 
    while a==True:
        print("\n Selecciona si vols:\n 1-afegir una infraccio \n 2-eliminar una infraccio \n 3-sortir")#mostrem per pantalla les tres opcions posibles
        x = input()#guardem l'imput
        if(x=="1"): #si vol afegir li preguntem quin vol afegir
            print("\n Has seleccionat afegir una infraccio, dona el codi de la infraccio a afegir") 
            y = input()
            if(y in infr):#si el valor ja esta a la llista ho comuniquem per pantalla per no tenir duplicatrs en cas que no ho estigui si que l'afegim utilitzant apend
                print("\n La infraccio ja estava a la llista \n")
            else: 
                infr.append(y)
        elif(x=="2"):#li comuniquem que ha seleccionat eliminar i li demanem el codi a eliminar
            print("\n Has seleccionat eliminar una infraccio, dona el codi de la infraccio a eliminar") 
            y = input()
            if(y in infr):#comprobem si el codi existeix, si existeix l'eliminem si no li comuniquem que el codi no esta a la llista
                infr.remove(y)
            else: 
                 print(" \n La infraccio no estava a la llista \n")
        elif(x=="3"):#canviem el valor del comprovant per sortir i li comuniquem que esta sortint
            print("\n Has seleccionat la opcio de sortir ")
            a=False
        else:# en cas que no posi un valor valid li diem quin son els valors valids i tornem
            print("\n Has de posar 1 2 o 3")
        print("\n La llista es \n")#mostrem per pantalla la llista
        print(infr)

<div style="background-color: #fcf2f2; border-color: #dfb5b4; border-left: 5px solid #dfb5b4; padding: 0.5em;">
<strong>Solució</strong>
</div>

In [24]:
app()

 Selecciona si vols:
 1-afegir una infraccio
 2-eliminar una infraccio
 3-sortir

 1

 Has seleccionat afegir una infraccio, dona el codi de la infraccio a afegir

 12

 La llista es

['12']

 Selecciona si vols:
 1-afegir una infraccio
 2-eliminar una infraccio
 3-sortir

 1

 Has seleccionat afegir una infraccio, dona el codi de la infraccio a afegir

 5

 La llista es

['12', '5']

 Selecciona si vols:
 1-afegir una infraccio
 2-eliminar una infraccio
 3-sortir

 1

 Has seleccionat afegir una infraccio, dona el codi de la infraccio a afegir

 7

 La llista es

['12', '5', '7']

 Selecciona si vols:
 1-afegir una infraccio
 2-eliminar una infraccio
 3-sortir

 1

 Has seleccionat afegir una infraccio, dona el codi de la infraccio a afegir

 5

 La infraccio ja estava a la llista


 La llista es

['12', '5', '7']

 Selecciona si vols:
 1-afegir una infraccio
 2-eliminar una infraccio
 3-sortir

 2

 Has seleccionat eliminar una infraccio, dona el codi de la infraccio a eliminar

 3

 La infraccio no estava a la llista


 La llista es

['12', '5', '7']

 Selecciona si vols:
 1-afegir una infraccio
 2-eliminar una infraccio
 3-sortir

 2

 Has seleccionat eliminar una infraccio, dona el codi de la infraccio a eliminar

 5

 La llista es

['12', '7']

 Selecciona si vols:
 1-afegir una infraccio
 2-eliminar una infraccio
 3-sortir

 3

 Has seleccionat la opcio de sortir

 La llista es

['12', '7']